<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
	    <ProjectType>ProgramLibrary</ProjectType>
    </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net8</TargetFramework>
    <RootNamespace>PepperDash.Essentials.DM</RootNamespace>
    <Deterministic>false</Deterministic>
    <AssemblyTitle>PepperDash.Essentials.DM</AssemblyTitle>
    <Description>This software is a PepperDash Essentials Plugin for PepperDash.Essentials.DM.</Description>    
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <OutputPath>4Series\bin\$(Configuration)\</OutputPath>    
    <PackageId>PepperDash.Essentials.Plugin.4Series.DM</PackageId>
    <PackageProjectUrl>https://github.com/PepperDash/PepperDash.Essentials.DM.git</PackageProjectUrl>
    <PackageTags>crestron net8 essentials plugin dm</PackageTags>
    <Product>PepperDash Essentials DM</Product>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>PepperDash Essentials DM Plugin</Title>    
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/PepperDash/PepperDash.Essentials.DM</RepositoryUrl>
    <PackageTags>crestron;net8;essentials;dm;</PackageTags>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugType>full</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PepperDashEssentials" Version="3.0.0-dev-v3-routing.63">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="Chassis\Config\Schema\DmChassisControllerPropertiesConfigSchema.json" />
    <None Include="LICENSE.md" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>
